### ISSUE TITLE
Can't import finetune while going through finetune_binary_classification.py 

### ISSUE THREAD

**Issue by katgre** [mwalmsley/zoobot#68]
I tried to go through finetune_binary_classification.py, but got the error:

ImportError: cannot import name 'finetune' from 'zoobot.pytorch.training' (/usr/local/lib/python3.8/dist-packages/zoobot/pytorch/training/__init__.py)

I tried it both with kasia and dev branch, went through "git clone" and "pip install" (I remembered there were some issues during Hackaton regarding that), also tried to import other features from the folder (i.e. losses) and it worked fine.

**Comment by mwalmsley** [comment]
Hi Kasia,

Today I have made a Colab notebook with the new finetuning example - https://colab.research.google.com/drive/17bb_KbA2J6yrIm4p4Ue_lEBHMNC1I9Jd?usp=sharing

Hopefully this will give you a starting point. I have updated the `kasia` branch to use exactly the same code as the branch I used for that notebook (`for-v1`)

Let me know if that fixes the issue please, otherwise I will need some more details to understand what's going wrong

**Comment by katgre** [comment]
Hi Mike,

I tried running the notebook and everything runs smoothly :> I'll work on the documentation and try to finish the finetune example before 28th December - I'll be at home till then and my Internet won't be so wonky xD

**Comment by mwalmsley** [comment]
Closing as working smoothly now
